version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: db-agent-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - a2a_network

  database_agent:
    build:
      context: .
      dockerfile: app/agents/database_agent/Dockerfile
    container_name: db-agent-database-agent
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10001:10001"
    env_file:
      - .env
    networks:
      - a2a_network
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:10001/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  host_agent:
    build:
      context: .
      dockerfile: app/agents/host/multiagent/Dockerfile
    container_name: db-agent-host-agent
    restart: always
    depends_on:
      database_agent:
        condition: service_started
    ports:
      - "10000:10000"
    env_file:
      - .env
    networks:
      - a2a_network

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: db-agent-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      database_agent:
        condition: service_started
      host_agent:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - a2a_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: db-agent-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "12000:12000"
    env_file:
      - .env
    networks:
      - a2a_network

volumes:
  postgres_data:

networks:
  a2a_network:
    driver: bridge
