version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: db-agent-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: db-agent-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: db-agent-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "12000:12000"
    env_file:
      - .env

volumes:
  postgres_data: 